//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Telar.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDB_INFO_SCREEN                 130
#define IDR_RetellSCRVwSetTYPE          130
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define ID_VIEW_NAVIGATION              185
#define IDB_NAVIGATION_LARGE            186
#define IDB_NAVIGATION_LARGE_HC         187
#define IDB_PAGES                       188
#define IDB_PAGES_HC                    189
#define IDB_PAGES_SMALL                 190
#define IDB_PAGES_SMALL_HC              191
#define ID_TOOLS_OPTIONS                220
#define ID_VIEW_CAPTION_BAR             221
#define IDB_INFO                        230
#define IDS_CAPTION_BUTTON              231
#define IDS_CAPTION_BUTTON_TIP          232
#define IDS_CAPTION_TEXT                233
#define IDS_CAPTION_IMAGE_TIP           234
#define IDS_CAPTION_IMAGE_TEXT          235
#define IDS_MYCALENDARS                 250
#define IDS_CALENDAR                    251
#define IDS_SHORTCUTS                   252
#define IDS_FOLDERS                     253
#define IDS_OUTLOOKBAR                  258
#define IDS_RIBBON_CAPTIONBAR           295
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EDIT_MENU                   306
#define IDB_INFOSIGN                    313
#define IDD_DIALOG1                     314
#define IDD_DATASOURCE                  314
#define IDC_LIST1                       1000
#define IDC_CONTROL_PANEL_SOUND         1001
#define IDC_MUTE_INPUT_LINE             1002
#define IDC_UPDATE                      2002
#define IDTRIAL                         2003
#define IDD_ABOUTBOX                    2100
#define IDS_ABOUTBOX                    2101
#define IDD_TELAR_DIALOG                2102
#define IDD_NERO_DIALOG                 2102
#define IDS_PROPSHT_CAPTION             2103
#define IDD_GB_ENTERRESPONSEKEY_DIALOG  2103
#define IDD_PROPPAGE1                   2104
#define IDS_TITEL                       2104
#define IDD_PROPPAGE2                   2105
#define IDS_TITEL2                      2105
#define IDD_PROPPAGE3                   2106
#define IDS_TITEL3                      2106
#define IDD_PROPPAGE4                   2107
#define IDD_PROPPAGE5                   2108
#define CG_IDD_PROGRESS                 2109
#define CG_IDS_PROGRESS_CAPTION         2110
#define IDS_PROPSHT_CAPTION1            2115
#define IDD_ARCHIVEWIZZARDPAGE1         2116
#define IDB_IMAGE_LIST                  2129
#define IDR_MAINFRAME_RECORDING         2129
#define IDB_DRAGDROP_MULTI              2130
#define IDD_PASSWORT                    2131
#define IDB_DRAGDROP                    2131
#define IDB_SUCHEN                      2134
#define IDB_REW                         2138
#define IDB_PLAY                        2140
#define IDB_PAUSE                       2141
#define IDB_STOP                        2142
#define IDB_FF                          2143
#define IDB_FF2                         2144
#define IDB_REW2                        2145
#define IDD_SUCHFILTER                  2147
#define IDB_EXPORT                      2148
#define IDD_GB_EDIT                     2149
#define IDB_DELETE                      2150
#define IDB_EDIT                        2151
#define IDD_ADD_FOLDER                  2152
#define IDB_ADD_ORDNER                  2155
#define IDB_DEL_ORDNER                  2156
#define IDB_EDIT_ORDNER                 2157
#define IDB_BG2                         2158
#define IDB_BG1                         2159
#define IDB_ROBOT                       2160
#define IDB_NO_ROBOT                    2161
#define IDB_BUTTONBITMAP                2162
#define IDB_BUTTONDOWN                  2163
#define IDB_NO_MANAUF                   2165
#define IDB_MANAUF                      2166
#define IDB_TRASHCAN                    2168
#define IDB_SPEAKER                     2169
#define IDB_CUTWIRE                     2170
#define IDB_MICROFON                    2171
#define IDB_SAMPLINGRATE                2172
#define IDB_HARDWARE                    2173
#define IDB_ANSCHLUSS                   2174
#define IDB_AUFNAHMESTART               2175
#define IDB_FALCON                      2176
#define IDD_ENTER_KEY                   2177
#define IDB_EXIT                        2178
#define IDD_ENTER_CONTACT_DETAILS       2179
#define IDD_EMAIL                       2180
#define IDD_GB_PROPPAGE5                2181
#define IDD_DETECT_SUPER_MODULAR        2181
#define IDD_GB_PROPPAGE4                2182
#define IDD_GB_PROPPAGE3                2183
#define IDB_INTELLIGENT                 2183
#define IDD_GB_PROPPAGE2                2184
#define IDD_GB_PROPPAGE1                2185
#define IDD_SELECT_DEVICE               2185
#define IDD_GB_PASSWORT                 2186
#define IDB_ACTIMAX_ON_GREY             2186
#define IDD_GB_PASSWORT_CHECK           2187
#define IDB_RETELL_ON_GREY              2187
#define IDD_PASSWORT_CHECK              2188
#define IDD_GB_SUCHFILTER               2189
#define IDD_EDIT                        2190
#define IDB_PHONECOACH_ON_GREY          2190
#define IDD_GB_ADD_FOLDER               2191
#define IDD_GB_PASSWORT_APPLICATION_LOCKED 2192
#define IDD_PASSWORT_APPLICATION_LOCKED 2193
#define IDD_E_ADD_FOLDER                2194
#define IDD_E_EDIT                      2195
#define IDD_E_PASSWORT                  2196
#define IDD_E_PASSWORT_APPLICATION_LOCKED 2197
#define IDD_E_PASSWORT_CHECK            2198
#define IDD_E_PROPPAGE2                 2199
#define IDD_E_SUCHFILTER                2200
#define IDD_AUTO_UPDATE_DIALOG          2200
#define IDD_ENTERRESPONSEKEY_DIALOG     2201
#define IDB_DISC                        2201
#define IDD_E_ENTERRESPONSEKEY_DIALOG   2202
#define IDB_WIZARD1                     2202
#define IDD_CZ_ADD_FOLDER               2203
#define IDB_DRAGDROP_COPY               2203
#define IDD_CZ_EDIT                     2204
#define IDB_DRAGDROP_MULTI_COPY         2204
#define IDD_CZ_ENTERRESPONSEKEY_DIALOG  2205
#define IDD_CZ_PASSWORT                 2206
#define IDD_CZ_PASSWORT_APPLICATION_LOCKED 2207
#define IDD_CZ_PASSWORT_CHECK           2208
#define IDB_SPEAKERVOLUME               2208
#define IDD_CZ_PROPPAGE2                2209
#define IDB_CONTROL_PANEL_SOUND         2209
#define IDD_NL_ADD_FOLDER               2210
#define IDB_SELECT_DEFAULT_OUTPUT_DEVICE 2210
#define IDD_NL_EDIT                     2211
#define IDD_NL_ENTERRESPONSEKEY_DIALOG  2212
#define IDD_NL_PASSWORT                 2213
#define IDD_NL_PASSWORT_APPLICATION_LOCKED 2214
#define IDD_NL_PASSWORT_CHECK           2215
#define IDD_NL_PROPPAGE2                2216
#define IDD_PL_PROPPAGE2                2217
#define IDB_MUTE_INPUT_LINE             2217
#define IDD_PL_PASSWORT_CHECK           2218
#define IDD_PL_PASSWORT_APPLICATION_LOCKED 2219
#define IDB_MUTE_MICROPHONE             2221
#define IDB_OPEN_MICROPHONE             2222
#define IDD_PL_ADD_FOLDER               2223
#define IDD_PL_ENTERRESPONSEKEY_DIALOG  2224
#define IDD_PL_EDIT                     2225
#define IDD_PL_PASSWORT                 2226
#define IDD_ARCHIVEWIZZARDPAGE2         2227
#define IDD_ARCHIVEWIZZARDPAGE3         2228
#define IDD_ARCHIVEWIZZARDPAGE4         2229
#define IDD_ARCHIVEWIZZARDPAGE5         2230
#define IDD_ARCHIVEWIZZARDPAGE7         2231
#define IDD_ARCHIVEWIZZARDPAGE6         2232
#define IDD_MUTEINPUT                   2234
#define IDC_PLAY                        21000
#define IDC_OPEN_CONTROL_PANEL          21000
#define IDC_EDIT_ORDNER                 21001
#define IDC_DATEINAME                   21002
#define IDC_NOTIZEN_OUTPUT              21002
#define IDC_IDENTIFIKATION              21002
#define IDC_PARTNER                     21002
#define IDC_DEFAULT                     21002
#define IDC_TEMP_FOLDER                 21002
#define IDC_DEVICES                     21002
#define IDC_SLIDER                      21003
#define IDC_NOTIZEN                     21003
#define IDC_INITIALEN                   21003
#define CG_IDC_PROGDLG_PROGRESS         21003
#define IDC_PFAD                        21003
#define IDC_PROGRESS1                   21003
#define IDC_START                       21004
#define CG_IDC_PROGDLG_PERCENT          21004
#define IDC_PASSWORT                    21005
#define IDC_MESSAGES                    21005
#define IDC_PAUSE                       21006
#define IDC_AUFNAHME                    21006
#define IDC_EMPFINDLICHKEIT             21006
#define IDC_ABORT                       21006
#define IDC_EMPFINDLICHKEIT_SLIDER      21006
#define IDC_FF                          21007
#define IDC_ABBRECHEN                   21007
#define IDC_SAMPLINGRATE                21007
#define IDC_PASSES                      21007
#define IDC_BEENDEN                     21008
#define IDC_MAINARCHIVE                 21008
#define IDC_REW                         21009
#define IDC_GESPRAECHSPARTNER           21009
#define IDC_DEVICE                      21009
#define IDC_NICHTBEACHTUNG              21009
#define IDC_ANSCHLUSS                   21010
#define IDC_NOTIZEN_TEXT                21010
#define IDC_DEL_ORDNER                  21010
#define IDC_LOESCHEN                    21010
#define IDC_NAME                        21011
#define IDC_INFO                        21011
#define IDC_MASTERPASSWORT              21011
#define IDC_LISTE                       21012
#define IDC_MUTE                        21012
#define IDC_SENSE_EXTENSION             21012
#define IDC_LISTE_FORMAT                21013
#define IDC_ORDNER                      21013
#define IDC_RESPONSECODE                21013
#define IDC_STOP                        21014
#define IDC_FEATURES                    21014
#define IDC_REQUESTCODE                 21014
#define IDC_POSITION                    21015
#define IDC_PEAKLEVEL                   21015
#define IDC_COPYTOCLIPBOARD             21015
#define IDC_REW2                        21016
#define IDC_TEST                        21016
#define IDC_MAPIMAIL                    21016
#define IDC_FF2                         21017
#define IDC_AUSSTEUERUNG                21017
#define IDC_PHONE                       21017
#define IDC_STATIC_AUSSTEUERUNG         21018
#define IDC_ADD_ORDNER                  21018
#define IDC_INTERNETMAIL                21018
#define IDC_RADIO1                      21019
#define IDC_SPEICHERN_IN                21019
#define IDC_WWW                         21019
#define IDC_ARCHIVE                     21019
#define IDC_RADIO2                      21020
#define IDC_RADIO3                      21021
#define IDC_VERGROESSERN_BEI_PEGEL      21021
#define IDC_VERSION                     21022
#define IDC_INTELLIGENT_RADIO2          21022
#define IDC_AUTOSTART                   21022
#define IDC_LETZTE_AUFNAHME             21023
#define IDC_INTELLIGENT_RADIO3          21023
#define IDC_ALC                         21023
#define IDC_MINIMIZE_AFTER              21024
#define IDC_HOMEPAGE                    21025
#define IDC_EMAIL                       21026
#define IDC_GESPRAECHSPARTNER_TEXT      21026
#define IDC_AUFNAHMEPEGEL_TEXT          21027
#define IDC_CONFIRM                     21027
#define IDC_SUCHEN                      21028
#define IDC_EXPORT                      21029
#define IDC_EDIT                        21030
#define IDC_LICENSE_INFO                21031
#define IDC_DELETE                      21031
#define IDC_SET_ROOT_PATH               21032
#define IDC_DELETE2                     21032
#define IDC_SET_MAINARCHIVE             21033
#define IDC_DELETE3                     21033
#define IDC_NOTIZ                       21034
#define IDC_DELETE4                     21034
#define IDC_SET_PATH                    21035
#define IDC_SAMPLINGRATE_STATIC         21037
#define IDC_GERAET_STATIC               21038
#define IDC_ANSCHLUSS_STATIC            21039
#define IDC_AUFNAHMESTART_STATIC        21040
#define IDC_SAMPLINGRATE_FRAME          21041
#define IDC_GERAET_FRAME                21042
#define IDC_CODEC_STATIC                21042
#define IDC_TEXT                        21043
#define IDC_ANSCHLUSS_FRAME             21043
#define IDC_FORMAT_STATIC               21043
#define IDC_AUFNAHMESTART_FRAME         21044
#define IDC_NAME_STATIC                 21044
#define IDC_TEXT2                       21044
#define IDC_FEATURES_STATIC             21045
#define IDC_INTELLIGENT_STATIC          21045
#define IDC_TEXT3                       21045
#define IDC_INTELLIGENT_FRAME           21046
#define IDC_DEFAULT_STATIC              21047
#define IDC_AUFNAHME_AUTOMATIK_STATIC   21048
#define IDC_INITIALEN_STATIC            21049
#define IDC_PASSWORT_STATIC             21050
#define IDC_PASSES_STATIC               21051
#define IDC_EMPFINDLICHKEIT_STATIC      21052
#define IDC_START_STATIC                21053
#define IDC_STOP_STATIC                 21054
#define IDC_VERGROESSERN_BEI_PEGEL_STATIC 21055
#define IDC_LICENSE_KEY                 21056
#define IDC_MAINARCHIVE_STATIC          21056
#define IDC_LICENSE_KEY_STATIC          21057
#define IDC_NICHTBEACHTUNG_STATIC       21057
#define IDC_ADVERTISING                 21058
#define IDC_LOESCHEN1_STATIC            21059
#define IDC_FROM                        21060
#define IDC_LOESCHEN2_STATIC            21060
#define IDC_DATUM_NACH                  21061
#define IDC_AUTOSTART_STATIC            21061
#define IDC_DATUM_VOR                   21062
#define IDC_ALC_STATIC                  21062
#define IDC_ZEIT_NACH                   21063
#define IDC_VENDOR_LOGO_FRAME           21063
#define IDC_ZEIT_VOR                    21064
#define IDC_MASTERPASSWORT_STATIC       21064
#define IDC_MIN_DAUER                   21065
#define IDC_MINIMIZE_AFTER_STATIC       21065
#define IDC_MAX_DAUER                   21066
#define IDC_AUTOSTART_STATIC_LONG       21066
#define IDC_STATIC_IDENTIFIKATION       21067
#define IDC_SENSE_EXTENSION_STATIC      21067
#define IDC_STATIC_GESPRAECHSPARTNER    21068
#define IDC_STATIC_NOTIZEN              21069
#define IDC_STATIC_DATUM                21070
#define IDC_STATIC_ZEIT1                21071
#define IDC_STATIC_ZEIT2                21072
#define IDC_STATIC_DATUM_NACH           21073
#define IDC_STATIC_DATUM_VOR            21074
#define IDC_STATIC_MIN_DAUER            21075
#define IDC_STATIC_MAX_DAUER            21076
#define IDC_STATIC_SUCHE_NACH_FRAME     21077
#define IDC_STATUS                      21079
#define IDC_STATUS_TEXT                 21081
#define IDC_VERSIONINFO                 21083
#define IDC_SELECT_MEDIUM               21086
#define IDC_METHOD1                     21087
#define IDC_METHOD2                     21088
#define IDC_STORAGE_CONSUMTION          21088
#define IDC_NUMBER_OF_RECORDINGS        21089
#define IDC_RECALCULATE                 21090
#define IDC_BROWSE_TEMP_FOLDER          21091
#define IDC_SPACE                       21092
#define IDC_PROGRESS                    21093
#define IDC_OPEN_TEMPORARY_FOLDER       21094
#define IDC_DELETE1                     21095
#define IDC_NERO_DIALOG                 21095
#define IDC_MESSAGE                     21096
#define IDC_VOLUME_NAME                 21097
#define IDC_BURN                        21098
#define IDC_STATIC_WARNING              21099
#define IDC_CONNECT_TO_SQL_SERVER       21101
#define IDC_CONNECT_TO_SENSE            21102
#define IDC_SPEAKERVOLUME               21106
#define IDC_EMPFINDLICHKEIT_ANZEIGE     21108
#define IDC_ANSCHLUSS_VISTA_MUTE        21109
#define IDC_STATIC0                     21110
#define IDC_STATIC1                     21111
#define IDC_STATIC2                     21112
#define IDC_STATIC3                     21113
#define IDC_STATIC4                     21114
#define IDC_SPEAKER_ICON                21115
#define IDC_START_SPIN                  21117
#define IDC_STOP_SPIN                   21118
#define IDC_VERGROESSERN_BEI_PEGEL_SPIN 21119
#define IDC_NICHTBEACHTUNG_SPIN         21120
#define IDC_SELECT_DEFAULT_OUTPUT_DEVICE 65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        315
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
